### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by j-calvert** [razbensimon/react-vis-timeline#2]
## Overview
I'm having the following problem when installing.  I'm honestly not sure if this is something to my org's setup, but it the stack looks like it's coming from open source tools used by Yarn.

## Steps to reproduce
`yarn add --dev react-vis-timeline
`

## Error
...
```
Processing dom-helpers-3.3.1...
Processing react-lifecycles-compat-3.0.4...
Processing vis-data-6.6.1...
Error: 'import' and 'export' may only appear at the top level
    at error (/data/sandcastle/boxes/www/scripts/third-party/node_modules/rollup/dist/rollup.js:168:15)
    at Module.error (/data/sandcastle/boxes/www/scripts/third-party/node_modules/rollup/dist/rollup.js:19072:9)
    at tryParse (/data/sandcastle/boxes/www/scripts/third-party/node_modules/rollup/dist/rollup.js:18763:16)
    at Module.setSource (/data/sandcastle/boxes/www/scripts/third-party/node_modules/rollup/dist/rollup.js:18818:24)
    at /data/sandcastle/boxes/www/scripts/third-party/node_modules/rollup/dist/rollup.js:21457:20
    at async build (/data/sandcastle/boxes/www/scripts/third-party/tromple/tromple.js:273:18)
    at async run (/data/sandcastle/boxes/www/scripts/third-party/tromple/tromple.js:425:22)
    at async runWithCatch (/data/sandcastle/boxes/www/scripts/third-party/tromple/tromple.js:488:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

### aka, How I came to try using this package:

If I 
`yarn add --dev vis-timeline vis-data
`
the install succeeds, but the timeline UI component malfunctions, and (I think) I see others having the same problem, as in
https://github.com/visjs/vis-timeline/issues/312 and https://github.com/visjs/vis-timeline/issues/510 .  Not related to this package, per-se, but also maybe not unrelated.  Anyways, if you have any experience/ideas how to circumvent this issue, that would also be very appreciated.

Thanks!

**Comment by razbensimon** [comment]
I don't see any sign related to this library. your error is about something with `import`-`export` keywords within your code, also maybe it's your rollup setup, idk.
also, look at `vis-timeline` docs. `vis-timeline` and `vis-data` should be installed manually because it is `peerDependency`.
but this library already installs it as a dependency for you.

**Comment by razbensimon** [comment]
I don't see any sign related to this library. your error is about something with `import`-`export` keywords within your code, also maybe it's your rollup setup, idk.
also, look at `vis-timeline` docs. `vis-timeline` and `vis-data` should be installed manually because it is `peerDependency`.
but this library already installs it as a dependency for you.
